### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by Ihtisham-Alii** [Umar-Waseem/OpenCL-and-Docker#2]
Whenever I change the host.c code and recompile it, it does not reflect in the output. It displays the same original output. Why is that?

**Comment by HafizHammadAhmed** [comment]
> Whenever I change the host.c code and recompile it, it does not reflect in the output. It displays the same original output. Why is that?

instead of the command docker run -it OpenCL-image
run the following command:
docker run -v "C:\Users\username\path\to\this\folder\OpenCL-and-Docker-main:/app" -it opencl-image

in the above command, just added   -v "address:/app"  in the command (docker run -it OpenCL-image).
it will now reflect the change in the output.
